export default [
  {
    login: "Nazareno95",
    id: 23666931,
    node_id: "MDQ6VXNlcjIzNjY2OTMx",
    avatar_url: "https://avatars.githubusercontent.com/u/23666931?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Nazareno95",
    html_url: "https://github.com/Nazareno95",
    followers_url: "https://api.github.com/users/Nazareno95/followers",
    following_url:
      "https://api.github.com/users/Nazareno95/following{/other_user}",
    gists_url: "https://api.github.com/users/Nazareno95/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Nazareno95/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Nazareno95/subscriptions",
    organizations_url: "https://api.github.com/users/Nazareno95/orgs",
    repos_url: "https://api.github.com/users/Nazareno95/repos",
    events_url: "https://api.github.com/users/Nazareno95/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Nazareno95/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "lpipeal",
    id: 33855375,
    node_id: "MDQ6VXNlcjMzODU1Mzc1",
    avatar_url: "https://avatars.githubusercontent.com/u/33855375?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/lpipeal",
    html_url: "https://github.com/lpipeal",
    followers_url: "https://api.github.com/users/lpipeal/followers",
    following_url:
      "https://api.github.com/users/lpipeal/following{/other_user}",
    gists_url: "https://api.github.com/users/lpipeal/gists{/gist_id}",
    starred_url: "https://api.github.com/users/lpipeal/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/lpipeal/subscriptions",
    organizations_url: "https://api.github.com/users/lpipeal/orgs",
    repos_url: "https://api.github.com/users/lpipeal/repos",
    events_url: "https://api.github.com/users/lpipeal/events{/privacy}",
    received_events_url: "https://api.github.com/users/lpipeal/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "AshlCabr020694",
    id: 45569099,
    node_id: "MDQ6VXNlcjQ1NTY5MDk5",
    avatar_url: "https://avatars.githubusercontent.com/u/45569099?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/AshlCabr020694",
    html_url: "https://github.com/AshlCabr020694",
    followers_url: "https://api.github.com/users/AshlCabr020694/followers",
    following_url:
      "https://api.github.com/users/AshlCabr020694/following{/other_user}",
    gists_url: "https://api.github.com/users/AshlCabr020694/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/AshlCabr020694/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/AshlCabr020694/subscriptions",
    organizations_url: "https://api.github.com/users/AshlCabr020694/orgs",
    repos_url: "https://api.github.com/users/AshlCabr020694/repos",
    events_url: "https://api.github.com/users/AshlCabr020694/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/AshlCabr020694/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "alexiscodec",
    id: 79610034,
    node_id: "MDQ6VXNlcjc5NjEwMDM0",
    avatar_url: "https://avatars.githubusercontent.com/u/79610034?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/alexiscodec",
    html_url: "https://github.com/alexiscodec",
    followers_url: "https://api.github.com/users/alexiscodec/followers",
    following_url:
      "https://api.github.com/users/alexiscodec/following{/other_user}",
    gists_url: "https://api.github.com/users/alexiscodec/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/alexiscodec/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/alexiscodec/subscriptions",
    organizations_url: "https://api.github.com/users/alexiscodec/orgs",
    repos_url: "https://api.github.com/users/alexiscodec/repos",
    events_url: "https://api.github.com/users/alexiscodec/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/alexiscodec/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "erickariasec",
    id: 86202597,
    node_id: "MDQ6VXNlcjg2MjAyNTk3",
    avatar_url: "https://avatars.githubusercontent.com/u/86202597?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/erickariasec",
    html_url: "https://github.com/erickariasec",
    followers_url: "https://api.github.com/users/erickariasec/followers",
    following_url:
      "https://api.github.com/users/erickariasec/following{/other_user}",
    gists_url: "https://api.github.com/users/erickariasec/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/erickariasec/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/erickariasec/subscriptions",
    organizations_url: "https://api.github.com/users/erickariasec/orgs",
    repos_url: "https://api.github.com/users/erickariasec/repos",
    events_url: "https://api.github.com/users/erickariasec/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/erickariasec/received_events",
    type: "User",
    site_admin: false,
  },
];
