export default {
  login: "rparias",
  id: 22307059,
  node_id: "MDQ6VXNlcjIyMzA3MDU5",
  avatar_url: "https://avatars.githubusercontent.com/u/22307059?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/rparias",
  html_url: "https://github.com/rparias",
  followers_url: "https://api.github.com/users/rparias/followers",
  following_url: "https://api.github.com/users/rparias/following{/other_user}",
  gists_url: "https://api.github.com/users/rparias/gists{/gist_id}",
  starred_url: "https://api.github.com/users/rparias/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/rparias/subscriptions",
  organizations_url: "https://api.github.com/users/rparias/orgs",
  repos_url: "https://api.github.com/users/rparias/repos",
  events_url: "https://api.github.com/users/rparias/events{/privacy}",
  received_events_url: "https://api.github.com/users/rparias/received_events",
  type: "User",
  site_admin: false,
  name: "Ronald Arias",
  company: "ThoughtWorks",
  blog: "",
  location: "Quito",
  email: null,
  hireable: null,
  bio: "Hi, my name is Ronald, I'm programmer and designer. I'm consultant developer at ThoughtWorks, I'm always willing to learn new things and collaborate in projects",
  twitter_username: "rparias",
  public_repos: 85,
  public_gists: 2,
  followers: 5,
  following: 2,
  created_at: "2016-09-19T22:01:02Z",
  updated_at: "2021-07-27T02:34:06Z",
};
